on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: Build static site
      run: yarn install && npm run build
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./dist/ s3://${{ secrets.AWS_BUCKET_NAME }} --delete
    - name: Grant All Users read access
      run: aws s3api put-bucket-acl --bucket ${{ secrets.AWS_BUCKET_NAME }} --grant-full-control id="${{ secrets.AWS_ACCOUNT_ID }}" --grant-read uri=http://acs.amazonaws.com/groups/global/AllUsers
    - name: Set as Static site
      run: aws s3 website s3://${{ secrets.AWS_BUCKET_NAME }}/ --index-document index.html --error-document error.html
